name : my-app

services:
  db:
    image: postgres:16
    container_name: my-contianer1
    environment:
      POSTGRES_PASSWORD: psotgres
      POSTGRES_USER: postgres
      POSTGRES_DB: postgres
    ports:
      - "5432:5432"
# this translate to docker -it --name=my-container1 -e POSTGRES_PASSWORD=psotgres -e POSTGRES_USER=postgres -e POSTGRES_DB: postgres -p 5432:5432 postgres:16
